# site information
title: sayo melu
description: ğŸ’» tech  âœ’ï¸ design  â˜•ï¸ life  ğŸ’® anime
url: https://sayo-melu.xyz
author: sayo melu
email: sayo-melu@outlook.com
logo: /asset/icon/logo.png # url of your logo or avatar
lang: zh-hans # language-territory
color: '#dc9fb4'
feed: true

podcast:
  title: sayo cast
  description: æ¬¢è¿æ¥åˆ° sayo cast. æˆ‘æ˜¯ sayo, ä¸€åçƒ­çˆ±æ€è€ƒçš„è®¡ç®—æœºä¸“ä¸šå­¦ç”Ÿ, è¿™æ˜¯ä¸€æ¡£å…³äºç”Ÿæ´», è®¾è®¡çš„æˆ‘çš„ä¸ªäººæ—¥è®°. 
  link: /podcast
  url: /podcast.xml
  author: sayo melu
  email: sayo-cast@outlook.com
  logo: /asset/icon/podcast-logo.png
  language: zh
  category: 'Society &amp; Culture'
  subcategory: 'Personal Journals'
  type: episodic
  explicit: false
  complete: 'no'
  block: 'no'

social:
  name: sayo melu
  links:
    - https://twitter.com/sayo-melu
    - https://github.com/sayo-melu
    - https://www.linkedin.com/in/sayomelu

comment:
  vssue:
    state: true
    owner: sayo-melu
    repo: sayo-blog
    clientID: 20ec7630039f76eae907
    clientSecret: 02be09c883a253670a1cf4fd158cbb3539d5f2d2
  disqus: # disqus shortname
  livere: # livere data-uid

analytic:
  google: # web tracking code

webmaster_verifications:
  bing:
  google:
  yandex:


# jekyll config
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap

include:

exclude:
  - cname
  - gemfile
  - gemfile.lock
  - license.txt
  - readme.md
  - page/notebook.html_backup
  - dat
  - vendor
