# site information
title: sayo melu
description: ğŸ³ï¸â€âš§ï¸ female â˜•ï¸ life ğŸµ music âœï¸ design ğŸ’» tech
url: https://anyuzu99.github.io/sayo-blog/
author: sayo melu
email: sayo-melu@outlook.com
logo: /asset/icon/logo.png # url of your logo or avatar
lang: zh-hans # language-territory
theme-color: '#dc9fb4'
feed: true

podcast:
  title: sayo cast
  description: æ¬¢è¿æ¥åˆ° sayo cast, è¿™æ˜¯ä¸€æ¡£å…³äºç”Ÿæ´», è®¾è®¡, æ€è€ƒçš„éŸ³é¢‘æ—¥è®°.
  link: /podcast
  url: /podcast.xml
  author: sayo melu
  email: sayo-cast@outlook.com
  logo: /asset/icon/podcast-logo.png
  language: zh
  category: 'Society &amp; Culture'
  subcategory: 'Personal Journals'
  type: episodic
  explicit: false
  complete: 'no'
  new-feed-url:

social:
  name: sayo melu
  links:
    - https://twitter.com/sayo-melu
    - https://github.com/sayo-melu
    - https://www.linkedin.com/in/sayomelu

comment:
  vssue:
    state: true
    owner: sayo-melu
    repo: sayo-blog
    clientID: 20ec7630039f76eae907
    clientSecret: 02be09c883a253670a1cf4fd158cbb3539d5f2d2
  disqus: # disqus shortname
  livere: # livere data-uid

analytic:
  google: # web tracking code

webmaster_verifications:
  bing:
  google:
  yandex:


# jekyll config
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap

include:

exclude:
  - cname
  - gemfile
  - gemfile.lock
  - license.txt
  - readme.md
  - page/notebook.html_backup
  - dat
  - vendor
